---
kind: pipeline
name: default
type: docker

platform:
  os: linux
  arch: arm64

steps:
  - name: build
    image: ghcr.io/codestation/drone-docker
    settings:
      buildkit: true
      cache: 
        - registry.megpoid.xyz/codestation/pgbackrest:${DRONE_BRANCH}-cache
      registry: registry.megpoid.xyz
      repo: registry.megpoid.xyz/codestation/pgbackrest
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    environment:
      GOPROXY:
        from_secret: goproxy_url

  - name: update
    image: plugins/webhook
    settings:
      urls: http://updater:8000/apis/swarm/v1/update
      token_value:
        from_secret: updater_apikey
      template: |
        {
          "images": [
            "registry.megpoid.xyz/codestation/pgbackrest:latest"
          ]
        }

trigger:
  branch:
  - master
