matrix:
  POSTGRES_VERSION:
    - 17
  PGBACKREST_VERSION:
    - 2.55.1

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:6.0.1
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/pgbackrest
      tags:
        - latest
        - ${PGBACKREST_VERSION}-postgres${POSTGRES_VERSION}
      build_args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - PGBACKREST_VERSION=${PGBACKREST_VERSION}
      config:
        from_secret: registry_credentials

when:
  event:
    - push
    - manual
  branch:
    - master
