matrix:
  POSTGRES_VERSION:
    - 17
  PGBACKREST_VERSION:
    - 2.54.2

steps:
  build:
    image: woodpeckerci/plugin-docker-buildx:5.2.1
    settings:
      registry: registry.megpoid.dev
      repo: registry.megpoid.dev/codestation/pgbackrest
      tags:
        - ${PGBACKREST_VERSION}-postgres${POSTGRES_VERSION}
        - latest
      build_args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - PGBACKREST_VERSION=${PGBACKREST_VERSION}
      config:
        from_secret: registry_credentials

when:
  event:
    - push
    - manual
  branch:
  - master
